helm:
  parameters:
  - name: image.tag
    value: 2094a8c3225102cd8314960532257c312a914b70-r1
    forcestring: true
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/start-admin
    forcestring: true
