helm:
  parameters:
  - name: image.tag
    value: b58e82d9293b326fad7d9eef076dbfde6da8d11c-r1
    forcestring: true
  - name: image.repository
    value: 771826808455.dkr.ecr.eu-west-1.amazonaws.com/wiki-mcp
    forcestring: true
